#' Import Spike Counts from idxstats Output
#'
#' Extracts the sample identifier from an idxstats file path, reads the tab-delimited 
#' count data, filters out unmapped or unplaced reads, and appends the sample ID.
#'
#' @param x Character string. The file path to a spike count text file (e.g., idxstats output).
#'
#' @return A tibble with five columns:
#' \describe{
#'   \item{Species}{Character. Name of the spiked-in reference species.}
#'   \item{Length}{Numeric. Sequence length of the reference genome.}
#'   \item{Count}{Numeric. Number of mapped reads.}
#'   \item{Unmapped}{Numeric. Number of unmapped reads.}
#'   \item{Sample}{Character. Extracted sample identifier.}
#' }
#' 
#' @importFrom stringr str_remove_all str_remove str_starts
#' @importFrom readr read_tsv
#' @importFrom dplyr filter mutate
#' @importFrom magrittr %>%
#' @export
import_spike_counts <- function(x) {

  sampleid <- stringr::str_remove_all(x, '.*\\/')
  sampleid <- stringr::str_remove(sampleid, '_spike.txt')

  readr::read_tsv(x, col_names = c('Species', 'Length', 'Count', 'Unmapped'), show_col_types = FALSE) %>%
    dplyr::filter(!stringr::str_starts(Species, '\\*')) %>%
    dplyr::mutate(Sample = sampleid)

}

#' Calculate Abundance Scaling Factors via Robust Regression
#'
#' Computes sample-specific scaling factors to normalize microbiome sequencing counts 
#' to absolute cell abundances. It normalizes spike counts by genome length, pairs them 
#' with known expected cell loads, and fits a robust linear regression model (RLM) 
#' forced through the origin ($Y \sim X + 0$).
#'
#' @param spike_counts A data frame or tibble containing the imported spike counts 
#' generated by \code{\value{import_spike_counts}}.
#' @param sample Character string. The specific sample ID to filter and calculate.
#' @param spike_expected A data frame or tibble containing the expected spike-in cell 
#' loads, requiring at least \code{Species} and \code{Expected_Cells} columns.
#'
#' @return A tibble with a single row containing three columns:
#' \describe{
#'   \item{Sample}{Character. The validated sample identifier.}
#'   \item{ScalingFactor}{Numeric. The calculated slope (coefficient) from the regression model, used for downstream multiplier normalization.}
#'   \item{Method}{Character. Details the calculation pathway used ("RLM: Robust Regression", "Manual: Single spike", or a failure state message).}
#' }
#' 
#' @importFrom dplyr filter mutate left_join tibble
#' @importFrom MASS rlm
#' @importFrom stats coef
#' @importFrom magrittr %>%
#' @export
calculate_scaling_factor <- function(spike_counts, sample, spike_expected) {
  
  # NOTE: spike_counts must exist in the environment or package data
  df <- spike_counts %>% 
    dplyr::filter(Sample == sample) %>%
    dplyr::mutate(ReadsNormalised = Count / Length) %>%
    dplyr::left_join(spike_expected, by = 'Species')
  
  if (nrow(df) < 1) {
    return(dplyr::tibble(Sample = sample,
                         ScalingFactor = 0, 
                         Method = "Failed: No spikes detected"))
  }
  
  if (nrow(df) == 1) {
    temp_factor <- df$Expected_Cells / df$ReadsNormalised
    return(dplyr::tibble(Sample = sample,
                         ScalingFactor = temp_factor, 
                         Method = "Manual: Single spike"))
  }
  
  tryCatch({
    # Model: Known_Cells ~ (Reads / Genome_Size)
    # + 0 forces the intercept through the origin (0 reads = 0 cells)
    model <- MASS::rlm(Expected_Cells ~ ReadsNormalised + 0, data = df)
    
    return(dplyr::tibble(Sample = sample,
                         ScalingFactor = stats::coef(model)[["ReadsNormalised"]], 
                         Method = "RLM: Robust Regression"))
  }, error = function(e) {
    return(dplyr::tibble(Sample = sample, 
                         ScalingFactor = 0, 
                         Method = "Failed: RLM Error"))
  })
}

